[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "options_pricing_bs"
version = "0.1.0"
dependencies = [
  "fastapi",
  "httpx",
  "yfinance",
  "scipy",
]
