name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest fastapi httpx scipy

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --maxfail=1 --disable-warnings -q

      # ---- Front-end / Jest ---- 

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install front-end dependencies
        run: npm ci
        working-directory: frontend

      - name: Run front-end unit tests
        run: npm test
        working-directory: frontend
